require('dotenv').config();
const express =require('express');
const app = express();
const cors=require("cors");
const connection = require("./db.js")
const mongoose = require("mongoose");
var bodyParser  = require('body-parser');
const nodemailer = require('nodemailer');


connection();

const taskSchema = mongoose.Schema({
    title:{
        type:String,
        required:true,
    } ,
    message:{
        type:String,
        required:true,
    },
    remind:{
        type:String,
        required:true,
    },
    user:{
        type:String,
        required:true,
    },
    status:{
        type:String,
        required:true,
    }
})

const Task = mongoose.model("task",taskSchema);
app.use(bodyParser.urlencoded());
app.use(bodyParser.json());
app.use(cors());

app.listen(2000,()=>{
    console.log("server is listening at 2000");
})

app.post('/addtask', async (req,res)=>{
     if(req.body)
     {
         const task= await Task.create(req.body);
         console.log(task);
     }
     res.send("hello from backend");
})



 var transport = nodemailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "d053188b794cf9", //generated by Mailtrap
      pass: "b746800f0abe08" //generated by Mailtrap
    }
  });





setInterval(async ()=>{
    let current = new Date();
    let time=current.getHours()+"/"+current.getMinutes();
    const task=await Task.find();
    let tasks=task.filter((item)=>{
       return item.remind===time
    }) 
    console.log(time);
    if(tasks.length!==0)
    {
    console.log(time)
    var mailOptions = {
        from: 'aksharma1998aksharma@gmail.com',
        to: 'akashsh215@gmail.com',
        subject: 'Nice Nodemailer test',
        text: 'Hey there, Here is you Reminder :)',
        html: ` <h1>Hey there, This is your Time to Complete the Task :)</h1>
                <p>Title : ${tasks[0].title}</p> <p>Message : ${tasks[0].message}</p> 
                <p>Time : ${tasks[0].remind}</p> <p>UserName : ${tasks[0].user}</p> 
                <p>Status : ${tasks[0].status}</p>`
    };
    transport.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log(error);
        }
        console.log('Message sent: %s', info.messageId);
    });
   }
},30000)